# Generated by Django 5.0.6 on 2026-10-01 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de fundación')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('beer_type', models.CharField(choices=[('lager', 'Lager'), ('ale', 'Ale'), ('stout', 'Stout'), ('porter', 'Porter'), ('ipa', 'IPA'), ('wheat', 'Wheat Beer'), ('sour', 'Sour'), ('other', 'Otro')], default='lager', max_length=20, verbose_name='Tipo')),
                ('alcohol_content', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Contenido de alcohol (%)')),
                ('ibu', models.PositiveIntegerField(blank=True, null=True, verbose_name='IBU')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image_url', models.URLField(blank=True, verbose_name='URL de imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beers', to='beers.brand', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Cerveza',
                'verbose_name_plural': 'Cervezas',
                'ordering': ['brand__name', 'name'],
            },
        ),
    ]
